### PR TITLE
AEROGEAR-3564 - use #nochrome link to hide navbar on docs

### PR DESCRIPTION
**Pull request by jasonmadigan**
See also: https://github.com/aerogear/antora-ui/pull/11

edit: waiting for https://github.com/aerogear/antora-ui/pull/13 to be deployed to docs.aerogear.org - change will become visible then (I hope!)

### CODE REVIEW

**Comment by aidenkeating** [comment]
:eyes:

**Comment by aidenkeating** [comment]
@jasonmadigan Sorry for the wait. It might just be local, but `docs.aerogear.org` is not rendering properly for me.

**Comment by jasonmadigan** [comment]
thank you @laurafitzgerald!

**Comment by jasonmadigan** [comment]
We'll hold off on merging until I get  https://github.com/aerogear/antora-ui/pull/13 merged and deployed

**Comment by jasonmadigan** [comment]
@laurafitzgerald @aidenkeating changes enabling this to be tested in aerogear/antora-ui#13 have been landed. Should be OK to do a quick test now?

**Review by aidenkeating — APPROVED** [review]
Verified

**Comment by laurafitzgerald** [comment]
@aidenkeating awesome thanks. will merge

**Pull request merged**
