### PR TITLE
 💄 WIP - fix device trust view

### PR DESCRIPTION
**Pull request by wei-lee**
- [x] layout update
- [x] update icons
- [x] add refresh button
- [x] wording based on the result
- [x] add warning message if score is too low

simulator screen shot - iphone 8 plus - 2018-06-11 at 17 51 53

### CODE REVIEW

**Comment by wei-lee** [comment]
ping @aidenkeating @ziccardi @secondsun @StephenCoady, mind taking a look?

**Review by aidenkeating — COMMENTED** [review]
This looks good to me so far, tried it out locally and everything works.

One small thing is that the other apps capitalise each word in the result table, nothing major though.

@ciaranRoche You're working on the Cordova equivalent? Might be worth taking a look and making sure everything syncs up.

**Review by StephenCoady — COMMENTED** [review]
Yeah looks good to me too. Looking at the acceptance criteria it hits everything. Also agree with yesterday that the coloured text is definitely better.

**Review by ciaranRoche — COMMENTED** [review]
Just one comment, @wei-lee should we have the fab the same blue color as the rest of the app or keep it a different color?
Everything else is same as Cordova :+1:

**Comment by wei-lee** [comment]
@ciaranRoche From the slide deck, the refresh button on android is orange? I think make it orange looks better :)

**Comment by wei-lee** [comment]
simulator screen shot - iphone 8 plus - 2018-06-12 at 12 56 18

**Comment by wei-lee** [comment]
@aidenkeating can you review this?

**Comment by aidenkeating** [comment]
:eyes:

**Review by aidenkeating — APPROVED** [review]
Verified locally. Looks good to me!

**Pull request merged**
