### PR TITLE
Aerogear 2936 update auth info

### PR DESCRIPTION
**Pull request by wei-lee**
update the auth details view according to the cordova template.

You can see the screenshot here: https://docs.google.com/presentation/d/1FZL-Wy5D_wUo5ADrfhpRBh-Ny2rGauI3_C8SBrlk6rw/edit#slide=id.g3c52d834c7_0_72

@aidenkeating @ciaranRoche mind taking a look?

### CODE REVIEW

**Comment by aidenkeating** [comment]
:eyes:

**Review by ciaranRoche — APPROVED** [review]
From the screenshot it looks good, a minor detail would be the `X` icon, we used the material design icon `close` in cordova, so there is a slight difference between them, other than that it looks good :+1:

**Comment by wei-lee** [comment]
@ciaranRoche cool. I was wondering why it looks different. Will fix it

**Comment by ciaranRoche** [comment]
@wei-lee the other icon we used was also from material design, `done`

**Review by aidenkeating — COMMENTED** [review]
Tried it out locally, looks good. We can use the material icons for the X's. Everything else works great!

I have fixed the nav issues etc. we noticed in my PR #33

**Comment by wei-lee** [comment]
@aidenkeating @ciaranRoche mind taking a look again? Should be fixed now. Thanks.

**Comment by aidenkeating** [comment]
@wei-lee Verified on a device. It works and looks good.

**Review by aidenkeating — APPROVED** [review]

**Pull request merged**
