### PR TITLE
AEROGEAR-2934 Update auth screen

### PR DESCRIPTION
**Pull request by aidenkeating**
* Remove the cert pinning service
* Update the nav bar colors
* Update auth screen

Screenshot: https://docs.google.com/presentation/d/1FZL-Wy5D_wUo5ADrfhpRBh-Ny2rGauI3_C8SBrlk6rw/edit#slide=id.g3c52d834c7_0_184

### CODE REVIEW

**Comment by aidenkeating** [comment]
@wei-lee @StephenCoady Mind taking a look?

**Comment by wei-lee** [comment]
looks good!

**Comment by StephenCoady** [comment]
👀

**Review by StephenCoady — APPROVED** [review]
verified on device, looks good.

**Comment by aidenkeating** [comment]
@wei-lee Mind taking one more look?

**Review by wei-lee — APPROVED** [review]

**Pull request merged**
