### PR TITLE
AEROGEAR-2925 Update app icons and display name

### PR DESCRIPTION
**Pull request by aidenkeating**
Currently the display name of the app is its Bundle Identifier.
Along with this its icon wasn't defined, causing an unattrative
default icon to be shown.

This adds the AeroGear icon to the app. It also updates the display
name of the app to be something more readable.

It should be noted that in iOS 11 a change was introduced which
removes spaces in apps with names larger than 12 characters. This
means no spaces show up in the app name.

### CODE REVIEW

**Comment by aidenkeating** [comment]
@wei-lee Would you mind taking a look? As I said in the commit message iOS 11 will remove spaces in app names longer than 12 characters. Not sure if that's an issue for us though. I have included an image below, it's the app second row on the right hand side. The icon set was generated from an SVG, so every icon is the correct size and Xcode is showing no warning.

screen shot 2018-06-07 at 17 05 01

Also, I have way too many dodgy dev apps installed, don't judge 😅

**Comment by wei-lee** [comment]
@aidenkeating I have verified the changes locally on emulators and they look good. Also you can add spaces to the appname: https://stackoverflow.com/questions/35495888/space-in-ios-app-name-is-not-showing. I have tried it and it works.

**Comment by aidenkeating** [comment]
screen shot 2018-06-08 at 11 43 39

@wei-lee Thanks for the review/verification. I have updated the `Info.plist` file to use the workaround in https://github.com/aerogear/ios-showcase-template/pull/25/commits/cf58a320276359cb7614d9df39815c045ced39ac. I was hesitant to use it because it looks like a hack that could be fixed. But I suppose the worst that could happen is they remove these spaces also.

**Comment by aidenkeating** [comment]
@laurafitzgerald To make you aware of the work on this

**Review by wei-lee — APPROVED** [review]

**Pull request merged**
