### PR TITLE
Added push feature

### PR DESCRIPTION
**Pull request by jhellar**
## Motivation

https://issues.jboss.org/browse/AEROGEAR-2519

# Changes

Added push feature from SDK example app.

### CODE REVIEW

**Comment by jhellar** [comment]
ping @TommyJ1994

**Review by wtrocki — CHANGES_REQUESTED** [review]
Classy work!

**Review by wtrocki — APPROVED** [review]
Classy work!

**Review by wei-lee — APPROVED** [review]
👍

**Pull request merged**
