### PR TITLE
AEROGEAR-2940 Update push notification UI

### PR DESCRIPTION
**Pull request by aidenkeating**
Update the UI of the push page to match the Cordova app.

Link: https://docs.google.com/presentation/d/1FZL-Wy5D_wUo5ADrfhpRBh-Ny2rGauI3_C8SBrlk6rw/edit#slide=id.g3c52d834c7_0_212

### CODE REVIEW

**Comment by aidenkeating** [comment]
@wei-lee Mind taking a look?

**Review by ciaranRoche — APPROVED** [review]
Looks good :+1:

**Comment by wei-lee** [comment]
looks good. The only thing is should the title be "Push Messages" or "Push Notifications", the latter is used in the cordova app. cc @ciaranRoche

**Comment by aidenkeating** [comment]
@wei-lee @ciaranRoche I noticed that difference too. `Push Messages`was used because it's the title of the subsection in the nav menu (based on https://issues.jboss.org/browse/AEROGEAR-2929), we follow the same pattern for the `Authentication` view (using the subsection name instead of the top level section). https://docs.google.com/presentation/d/1FZL-Wy5D_wUo5ADrfhpRBh-Ny2rGauI3_C8SBrlk6rw/edit#slide=id.g3c52d834c7_0_184

**Comment by aidenkeating** [comment]
I still need to verify some changes on a real device so adding a do not merge to this

**Comment by aidenkeating** [comment]
Attached a screenshot of it running on a real device below.

screen shot 2018-06-18 at 09 03 35

**Comment by aidenkeating** [comment]
@wei-lee Mind taking another look? Tested it out on a real device and it works fine (see screenshot from device above)

**Comment by wei-lee** [comment]
@aidenkeating looks good!

**Pull request merged**
