### PR TITLE
 💄 update style of the submenu item

### PR DESCRIPTION
**Pull request by wei-lee**
screen shot 2018-06-26 at 18 02 24

@jasonmadigan @johnfriz What do you think of the updated nav menu?

### CODE REVIEW

**Comment by johnfriz** [comment]
@wei-lee - Thanks, it looks better already. Could we drop the font another little bit and decrease the padding on top and bottom - just want to emphasis the fact that they are sub menu items.

Have attached a mockup to illustrate what I mean... 

@jasonmadigan - thoughts?

41927850-480200c8-796b-11e8-9bf0-790518d3a872

**Comment by jasonmadigan** [comment]
@wei-lee @johnfriz like the change, it's much better. Makes it much clearer that this is sub-nav. I think smaller text would be OK, but I'd have a small Fitt's Law concern that would say keep the hit/tap area the same size so it's not fiddly to click. If that's easy/possible it'd be a win/win?

One small nit (which I know @wei-lee will kill me for) - the spacing between the Icon & the text is a little on the extreme side IMHO - I'd half it.

**Comment by aidenkeating** [comment]
@johnfriz @jasonmadigan Does it make sense to keep the dividers if we're going with this approach? To me, something like following looks a bit cleaner (but I have no UI/UX knowledge). From the Cordova app

screen shot 2018-06-27 at 11 36 02

**Comment by jasonmadigan** [comment]
@aidenkeating I do like the look of that aesthetically

**Comment by wei-lee** [comment]
screen shot 2018-07-02 at 11 05 03

@aidenkeating @jasonmadigan is this one ok?

**Comment by aidenkeating** [comment]
@wei-lee This looks good to me, I'll try it out really quick

**Comment by wei-lee** [comment]
@aidenkeating I still need to fix the style of the selected item.

**Comment by wei-lee** [comment]
screen shot 2018-07-02 at 21 36 08

**Comment by wei-lee** [comment]
@aidenkeating now it's ready

**Review by aidenkeating — APPROVED** [review]
@wei-lee Tried it out on a device. Mostly looks good.

The only thing I'd say is the background is very dark compared with the orange foreground?  `UIColor(named: "Lightgrey")` seems closer to the other screenshots.

**Comment by wei-lee** [comment]
@aidenkeating good catch. I meant to use that colour but used the wrong constructor!

**Comment by wei-lee** [comment]
screen shot 2018-07-03 at 09 41 43

@aidenkeating Should be right this time.

**Review by aidenkeating — APPROVED** [review]
Tried it out, looks good!

**Pull request merged**
