### PR TITLE
AEROGEAR-3063 Gracefully fail if service configuration is not found

### PR DESCRIPTION
**Pull request by aidenkeating**
To be used with https://github.com/aerogear/aerogear-ios-sdk/pull/131

# Verification steps

* Clone https://github.com/aerogear/aerogear-ios-sdk/pull/131
* Run `./scripts/cloneShowcase.sh` and checkout this branch
* Run the app with the default `mobile-services.json` and ensure everything works
* Run the app with Keycloak config removed and ensure it works, but the dialog is shown on the Authenticate screen
* Run the app with Push config removed and ensure it works, but the dialog is shown on the Push Messages screen

### CODE REVIEW

**Comment by aidenkeating** [comment]
@wei-lee @StephenCoady   Would you mind taking a look? I had to modify https://github.com/aerogear/aerogear-ios-sdk/blob/master/modules/push/AgsPush.swift because it doesn't expose any errors to the end user currently. There's some access control stuff that will be removed before this gets merged in another PR #37

**Comment by StephenCoady** [comment]
👀

**Review by StephenCoady — APPROVED** [review]
verified this is working as expected on device and simulator.

**Comment by aidenkeating** [comment]
@wei-lee At the moment this is launching a browser with the docs page. Do we want to follow the same approach as #42 and instead embed the window in our app?

**Comment by wei-lee** [comment]
@aidenkeating yes, I think so. I think android app is doing the same

**Comment by aidenkeating** [comment]
@wei-lee Updated to use the newly published SDKs. Screenshots below:

* https://docs.google.com/presentation/d/1FZL-Wy5D_wUo5ADrfhpRBh-Ny2rGauI3_C8SBrlk6rw/edit#slide=id.g3d1a0ca8ff_18_1
* https://docs.google.com/presentation/d/1FZL-Wy5D_wUo5ADrfhpRBh-Ny2rGauI3_C8SBrlk6rw/edit#slide=id.g3c07eff8b6_30_3

**Comment by wei-lee** [comment]
I have verified it on an ios device.

**Pull request merged**
