### PR TITLE
 ⬆ use pre-release version of the sdk

### PR DESCRIPTION
**Pull request by wei-lee**

### CODE REVIEW

**Comment by wei-lee** [comment]
@wtrocki @aidenkeating  mind reviewing this so I can tag the release? Thanks.

**Review by aidenkeating — APPROVED** [review]
@wei-lee Tried the app out with the updated dependencies, everything seems to be working fine!

**Comment by wtrocki** [comment]
Testing.

**Review by wtrocki — APPROVED** [review]

**Comment by wtrocki** [comment]
Verified:
- Metrics
- Push
- Auth

**Pull request merged**
